Update and Deprecate Dicta-Sign
sign-language-processing/sign-language-processing.github.io pull request #108
Opened 2024-06-26 20:42 UTC by cleong110

Deprecation:
* https://www.sign-lang.uni-hamburg.de/dicta-sign/portal/index.html is in disrepair, and it is not clear that the data can actually be downloaded. There are many broken links. Videos do not consistently play.

Features:
* I have seen evidence of video, HamNoSys and glosses. 
* [However the sign_language_datasets loader](https://github.com/sign-language-processing/datasets/blob/master/sign_language_datasets/datasets/dicta_sign/dicta_sign.py) has also got pose and a few other features?  Not sure about this.

2024-06-26 21:31 UTC, AmitMY requested changes

2024-06-26 21:31 UTC, AmitMY commented on src/datasets/Dicta_Sign.json
> +  "status": "deprecated",
hmmm not so sure. it was used as recently as 2022 in Ham2Pose. the features are correct, and I agree they have broken links, but I'm not sure if it should be deprecated - I have contacts at hamburg, I can try to ask them to revive it

2024-06-26 21:44 UTC, cleong110 commented on src/datasets/Dicta_Sign.json
> +  "status": "deprecated",
Oh, good to know! I'll un-deprecate it for now, we can always re-add it late. Hmmm or maybe we could add a new status along the lines of "unsure"

2024-06-27 13:29 UTC, AmitMY approved these changes

2024-06-27 13:29 UTC, merged