Feature/fix bare citations script
sign-language-processing/sign-language-processing.github.io pull request #115
Opened 2024-06-28 17:25 UTC by cleong110

Fixes #113

2024-06-29 09:10 UTC, AmitMY requested changes

2024-06-29 09:10 UTC, AmitMY commented on Makefile
> +	python src/fix_bare_citations.py src/references.bib $@
i think it would be best if this was not a "fixer" (since it does not fix the source code, and allows us to write errors)
instead, i think this should be a "linter" - write a small github action that runs this script, and throws an error if this happens.
then you get quick feedback in the PR

2024-07-01 14:44 UTC, cleong110 commented
That would be better! I will set that up

On Sat, Jun 29, 2024 at 5:10 AM Amit Moryossef ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In Makefile
> <https://github.com/sign-language-processing/sign-language-processing.github.io/pull/115#discussion_r1659675570>
> :
>
> > @@ -18,6 +18,7 @@ dst/thesis.pdf: dst/index_shortcode.md src/references.bib
>
>  dst/index.md: src/index.md src/markdown_fix.sh src/formats.md dst tmp/datasets.md dst/assets
>  	cat src/index.md > $@
> +	python src/fix_bare_citations.py src/references.bib $@
>
> i think it would be best if this was not a "fixer" (since it does not fix
> the source code, and allows us to write errors)
> instead, i think this should be a "linter" - write a small github action
> that runs this script, and throws an error if this happens.
> then you get quick feedback in the PR
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sign-language-processing/sign-language-processing.github.io/pull/115#pullrequestreview-2149410431>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5FSTNLXVPFYQOV7L27JDBTZJZ2ZHAVCNFSM6AAAAABKCIQ44CVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNBZGQYTANBTGE>
> .
> You are receiving this because you authored the thread.Message ID:
> <sign-language-processing/sign-language-processing.github.
> ***@***.***>
>

2024-07-01 16:07 UTC, cleong110 commented on Makefile
> +	python src/fix_bare_citations.py src/references.bib $@
Done!

2024-07-01 16:09 UTC, cleong110 commented
Updated the script, renamed it, added a deploy action that calls it. Should now give an error on PR if there is a bare citation. 

Also it no longer bugs you about citations in comments

2024-07-01 21:24 UTC, AmitMY requested changes

2024-07-01 21:24 UTC, AmitMY commented on src/find_bare_citations.py
> +    if len(sys.argv) != 3:
always use `argparse` - so much more readable and convenient than sys.argv

2024-07-01 21:24 UTC, AmitMY commented on src/find_bare_citations.py
> +        print(f"Usage: {sys.argv[0]} <bib_file_path> <markdown_file_path>")
argparse will also take care of this

2024-07-01 21:24 UTC, AmitMY commented on src/find_bare_citations.py
> +                    issues.append(
use `yield` instead of appending to an array and returning the array. more economic that way

2024-07-01 21:24 UTC, AmitMY commented on src/find_bare_citations.py
> +    for i, line in enumerate(content):
this is quite inefficient - for every line, for every citation.
a better approach could be:

1. remove all comments from content (`re.sub` of `<!--[\s\S]*-->` probably)
2. remove all code blocks from content (similar to above)

then just `for each citation` check if it is in content

it will make the code a lot cleaner (no need to check in code block / in citation)

2024-07-01 21:24 UTC, AmitMY commented on src/find_bare_citations.py
> +            match = re.match(r"@\w+\{([^,]+),", line)
you could run this match on the entire content, why line by line?

2024-07-02 14:06 UTC, cleong110 commented on src/find_bare_citations.py
> +    if len(sys.argv) != 3:
Good call! Will do.

2024-07-02 14:09 UTC, cleong110 commented on src/find_bare_citations.py
> +            match = re.match(r"@\w+\{([^,]+),", line)
Didn't think of it, tbh. Not familiar with regex, got ChatGPT to help me write it. 

Although, if we do the entire content could we still extract line numbers?

2024-07-02 14:10 UTC, cleong110 commented on src/find_bare_citations.py
> +                    issues.append(
I will have to read up on how that works, I'll give it a go

2024-07-02 14:12 UTC, cleong110 commented on src/find_bare_citations.py
> +    for i, line in enumerate(content):
My testing was entirely focused on "does it function", I didn't think about ways to make it more efficient.

2024-07-02 14:26 UTC, cleong110 commented on src/find_bare_citations.py
> +            match = re.match(r"@\w+\{([^,]+),", line)
The original conversation was at https://chatgpt.com/share/68cde216-5aeb-41e1-a4b2-93e0855f6b98.

Note to self: ChatGPT output seems to be more trouble than it's worth sometimes, requiring significant revision. Maybe just use it for the regex part next time

2024-07-02 15:05 UTC, cleong110 commented on src/find_bare_citations.py
> +    for i, line in enumerate(content):
OK, wrote something to extend the citation key list by random strings and re-benchmark. 
```
python find_bare_citations.py ./references.bib ./index.md
Bibliography had 393 citations, checking for bare citations:
Bare-citation check complete after ~1.75 seconds
Bibliography had 493 citations, checking for bare citations:
Bare-citation check complete after ~2.24 seconds
Bibliography had 593 citations, checking for bare citations:
Bare-citation check complete after ~2.73 seconds
Bibliography had 693 citations, checking for bare citations:
Bare-citation check complete after ~3.16 seconds
Bibliography had 793 citations, checking for bare citations:
Bare-citation check complete after ~3.68 seconds
Bibliography had 893 citations, checking for bare citations:
Bare-citation check complete after ~4.18 seconds
Bibliography had 993 citations, checking for bare citations:
Bare-citation check complete after ~4.56 seconds
Bibliography had 1093 citations, checking for bare citations:
Bare-citation check complete after ~5.01 seconds
Bibliography had 1193 citations, checking for bare citations:
Bare-citation check complete after ~5.45 seconds
Bibliography had 1293 citations, checking for bare citations:
Bare-citation check complete after ~5.94 seconds
Bibliography had 1393 citations, checking for bare citations:
Bare-citation check complete after ~6.40 seconds
Bibliography had 1493 citations, checking for bare citations:
Bare-citation check complete after ~6.87 seconds
Bibliography had 1593 citations, checking for bare citations:
Bare-citation check complete after ~7.49 seconds
Bibliography had 1693 citations, checking for bare citations:
Bare-citation check complete after ~7.87 seconds
Bibliography had 1793 citations, checking for bare citations:
Bare-citation check complete after ~8.58 seconds
Bibliography had 1893 citations, checking for bare citations:
Bare-citation check complete after ~8.88 seconds
Bibliography had 1993 citations, checking for bare citations:
Bare-citation check complete after ~9.37 seconds
Bibliography had 2093 citations, checking for bare citations:
Bare-citation check complete after ~9.96 seconds
Bibliography had 2193 citations, checking for bare citations:
Bare-citation check complete after ~10.39 seconds
```

![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/122366389/71332dbf-9305-429e-8379-8cfb3ced516b)

So here's the growth curve to beat. 

I suppose the other thing to check would be to add lines to index.md and see how that affects things, but I think this is good enough

2024-07-02 18:53 UTC, cleong110 commented on src/find_bare_citations.py
> +    for i, line in enumerate(content):
Rewrote it to:

1. strip out comments
2. strip out code blocks
3. Not split content into lines
4. find all matches of bare citation keys
5. **Now we cannot return line numbers,** so instead we return the whole line in which a bare citation is found

Benchmarking results using the same procedure as above:
```
python find_bare_citations.py ./references.bib ./index.md 
Bibliography had 393 citations, checking for bare citations:
Bare-citation-check complete after ~0.76 seconds
Bibliography had 493 citations, checking for bare citations:
Bare-citation-check complete after ~0.92 seconds
Bibliography had 593 citations, checking for bare citations:
Bare-citation-check complete after ~1.09 seconds
Bibliography had 693 citations, checking for bare citations:
Bare-citation-check complete after ~1.30 seconds
Bibliography had 793 citations, checking for bare citations:
Bare-citation-check complete after ~1.50 seconds
Bibliography had 893 citations, checking for bare citations:
Bare-citation-check complete after ~1.65 seconds
Bibliography had 993 citations, checking for bare citations:
Bare-citation-check complete after ~1.83 seconds
Bibliography had 1093 citations, checking for bare citations:
Bare-citation-check complete after ~1.99 seconds
Bibliography had 1193 citations, checking for bare citations:
Bare-citation-check complete after ~2.16 seconds
Bibliography had 1293 citations, checking for bare citations:
Bare-citation-check complete after ~2.35 seconds
Bibliography had 1393 citations, checking for bare citations:
Bare-citation-check complete after ~2.53 seconds
Bibliography had 1493 citations, checking for bare citations:
Bare-citation-check complete after ~2.72 seconds
Bibliography had 1593 citations, checking for bare citations:
Bare-citation-check complete after ~2.88 seconds
Bibliography had 1693 citations, checking for bare citations:
Bare-citation-check complete after ~3.20 seconds
Bibliography had 1793 citations, checking for bare citations:
Bare-citation-check complete after ~3.50 seconds
Bibliography had 1893 citations, checking for bare citations:
Bare-citation-check complete after ~3.55 seconds
Bibliography had 1993 citations, checking for bare citations:
Bare-citation-check complete after ~3.66 seconds
Bibliography had 2093 citations, checking for bare citations:
Bare-citation-check complete after ~3.87 seconds
Bibliography had 2193 citations, checking for bare citations:
Bare-citation-check complete after ~4.12 seconds
```

So ~~significantly~~ a lot faster when we get to high citation counts.

2024-07-02 19:03 UTC, cleong110 commented on src/find_bare_citations.py
> +    for i, line in enumerate(content):
[893fecf](https://github.com/sign-language-processing/sign-language-processing.github.io/pull/115/commits/893fecf199a50705ddeab154db46e8e3b13266bc) should resolve this one.

2024-07-02 19:22 UTC, cleong110 commented on src/find_bare_citations.py
> +                    issues.append(
This change had a _dramatic_ speed-up effect on the function itself, as in the `find_bare_citations()` now takes 0.0 seconds. Iterating through the results does then take time. 

If I wish to output the lines  on which matches were found, the benchmarking results with `yield` look identical. 

```
python find_bare_citations.py ./references.bib ./index.md 
Bibliography had 393 citations, checking for bare citations:
Bare-citation check complete after ~0.74 seconds
Bibliography had 493 citations, checking for bare citations:
Bare-citation check complete after ~0.92 seconds
Bibliography had 593 citations, checking for bare citations:
Bare-citation check complete after ~1.09 seconds
Bibliography had 693 citations, checking for bare citations:
Bare-citation check complete after ~1.27 seconds
Bibliography had 793 citations, checking for bare citations:
Bare-citation check complete after ~1.49 seconds
Bibliography had 893 citations, checking for bare citations:
Bare-citation check complete after ~1.69 seconds
Bibliography had 993 citations, checking for bare citations:
Bare-citation check complete after ~1.83 seconds
Bibliography had 1093 citations, checking for bare citations:
Bare-citation check complete after ~2.00 seconds
Bibliography had 1193 citations, checking for bare citations:
Bare-citation check complete after ~2.17 seconds
Bibliography had 1293 citations, checking for bare citations:
Bare-citation check complete after ~2.36 seconds
Bibliography had 1393 citations, checking for bare citations:
Bare-citation check complete after ~2.69 seconds
Bibliography had 1493 citations, checking for bare citations:
Bare-citation check complete after ~2.82 seconds
Bibliography had 1593 citations, checking for bare citations:
Bare-citation check complete after ~2.97 seconds
Bibliography had 1693 citations, checking for bare citations:
Bare-citation check complete after ~3.19 seconds
Bibliography had 1793 citations, checking for bare citations:
Bare-citation check complete after ~3.63 seconds
Bibliography had 1893 citations, checking for bare citations:
Bare-citation check complete after ~3.54 seconds
Bibliography had 1993 citations, checking for bare citations:
Bare-citation check complete after ~3.71 seconds
Bibliography had 2093 citations, checking for bare citations:
Bare-citation check complete after ~3.91 seconds
Bibliography had 2193 citations, checking for bare citations:
Bare-citation check complete after ~4.18 seconds
Bibliography had 2293 citations, checking for bare citations:
Bare-citation check complete after ~4.32 seconds
```

Compare with https://github.com/sign-language-processing/sign-language-processing.github.io/pull/115#discussion_r1663016266, almost the same.

2024-07-13 08:56 UTC, AmitMY requested changes

2024-07-13 08:56 UTC, AmitMY commented on src/find_bare_citations.py
> +                citation_keys.append(match.group(1))
seems like you didn't understand my note.

You can run `re. findall` on the ENTIRE file, and just extract all matches, without iterating line by line.
![image](https://github.com/user-attachments/assets/d99df896-1c59-4d13-b8d2-a4c45664435a)

2024-07-13 08:56 UTC, AmitMY commented on src/find_bare_citations.py
> +    for citation_key in citation_keys:
the faster way to doing this would be to first only search for the `citation_key` without a `@` (simple regex, single pass)
then, once finding it, extract the entire line using the match index.

right now, it will do lots of back-searches

2024-07-15 17:48 UTC, cleong110 commented on src/find_bare_citations.py
> +                citation_keys.append(match.group(1))
No I understood, I don't know why it still has a "for line" in there. I'm pretty sure I took that out.

2024-07-15 17:59 UTC, cleong110 commented on src/find_bare_citations.py
> +                citation_keys.append(match.group(1))
Ah, dug into it: I thought this whole time we were trying to improve the regex for matching citations with index.md, not the regex for pulling citations out of references.bi

2024-07-15 18:11 UTC, cleong110 commented on src/find_bare_citations.py
> +                citation_keys.append(match.group(1))
Adding a "timeit" around the extraction-citations, I find that extracting the citations takes 0.0021669249999831663, is this worth fixing?

2024-07-15 18:29 UTC, cleong110 commented on src/find_bare_citations.py
> +    for citation_key in citation_keys:
I don't understand, sorry. I am learning regexes for the first time here. Are we not doing exactly that? Line 39 is some kind of regex that searches the whole string of index.md, and then if there's a bare citation we go and extract the line in line using finditer. 

.search() only finds the first match, I wanted all matches, and the lines they are on.

I picked finditer because https://docs.python.org/3/library/re.html#re.finditer seemed to allow us to find all the matches.

findall would seem to be a possibility but the documentation isn't clear to me on how to get the full line, or what the return type is (I think just strings?), and also it wouldn't then work with `yield`-ing one bare-citation issue. 

I guess I could try to rewrite it to findall and then yield the list? If it does return a list? And then I don't know how the Match indexes come into this

2024-07-15 18:46 UTC, cleong110 commented on src/find_bare_citations.py
> +    for citation_key in citation_keys:
Tried switching to findall(), and eliminated search(). 

```
def find_bare_citations(markdown_file_path:Path, citation_keys:list)->list:
    
    content = markdown_file_path.read_text()

    # Remove HTML comments. regex from https://stackoverflow.com/a/28208465
    content = re.sub("(<!--.*?-->)", "", content, flags=re.DOTALL)

    # Remove Markdown code blocks, regex from https://stackoverflow.com/a/64116935
    markdown_code_block_pattern = re.compile(r'```[^`]*```', re.DOTALL)

    content = markdown_code_block_pattern.sub('', content)

    for citation_key in citation_keys:

        # magical regex from ChatGPT: captures the whole line that has a bare citation.
        pattern = re.compile(r'^.*(?<!@)(?:' + re.escape(citation_key) + r').*$', re.MULTILINE)

        # Find all matching lines
        matches = pattern.findall(content)
        if matches:
            issue_tuple = citation_key, matches
            yield issue_tuple
            
```
timing this, the time did go down, from 0.65 to 0.62 seconds. I'm guessing most of the issue is in the regex itself, which I do not know how to edit.

2024-07-15 18:49 UTC, cleong110 commented on src/find_bare_citations.py
> +    for citation_key in citation_keys:
Yup, if I add timeit calls around `matches = pattern.findall(content)`, it is taking up 0.60 of the 0.62 seconds. 

```
    regex_times = []

    for citation_key in citation_keys:

        # magical regex from ChatGPT: captures the whole line that has a bare citation.
        pattern = re.compile(r'^.*(?<!@)(?:' + re.escape(citation_key) + r').*$', re.MULTILINE)

        # Find all matching lines
        start_time = timeit.default_timer()
        matches = pattern.findall(content)
        regex_time = timeit.default_timer() -start_time
        regex_times.append(regex_time)
        if matches:
            issue_tuple = citation_key, matches
            yield issue_tuple

    print(f"Total time spent in findall calls: {sum(regex_times)}")
```

2024-07-15 19:09 UTC, cleong110 commented on src/find_bare_citations.py
> +    for citation_key in citation_keys:
OK, [had it explained to me another way](https://chatgpt.com/share/3c145c68-dc38-43f0-a2b1-27d3cd1d43f5), "simple regex, single pass" literally means 


```
# Find all positions of the citation key without the @ symbol
        key_pattern = re.compile(re.escape(citation_key))
```
As in, just find that exact string anywhere.

tl;dr, don't try to do EVERYTHING in the regex all at once. Finding the citation key is blazing fast with a regex, then finding newlines is not hard, and then seeing if there's an @ in front is a simple check.

2024-07-15 19:23 UTC, cleong110 commented on src/find_bare_citations.py
> +                citation_keys.append(match.group(1))
Well, it wasn't that hard to fix once I figured out the other one. Editing this part to ALSO not go line-by-line, we save 

0.0021669249999831663 seconds - 0.0006211190002431977 seconds = 1.545806 milliseconds according to Google.

2024-07-16 13:22 UTC, AmitMY requested changes

2024-07-16 13:22 UTC, AmitMY commented on src/find_bare_citations.py
> +                matches.append(line)
after findging the `start_index`, this `if` should happen.
only then, if it did match, then you should look for `line_start`, `line_end`, etc
will not really change performance, but just better code

2024-07-16 13:22 UTC, AmitMY commented on src/find_bare_citations.py
> +            yield issue_tuple
```
yield citation_key, matches
```

2024-07-16 14:17 UTC, cleong110 commented on src/find_bare_citations.py
> +            yield issue_tuple
That makes more sense

2024-07-16 14:18 UTC, cleong110 commented on src/find_bare_citations.py
> +                matches.append(line)
True, the rest of the code is redundant otherwise, might as well exit early.

2024-07-16 14:54 UTC, cleong110 commented
One thing I haven't been able to figure out is how to find the line number of an issue in the original content. 

I tried 
```
lines = content.splitlines()
```

followed later by 
```
line_index = lines.index(line)
```

Which adds almost zero overhead to run time. That was cool, I thought. 

But upon testing I found that if there's two identical lines for whatever reason, it will always find the first one.

2024-07-16 15:23 UTC, cleong110 commented
Another nice-to-have would be to show the index in the line, something like 

```
line 21, column 33:
    lorem ipsum foo_etal_2024 dolor sit amet
                            ^
```
And I got something working, but it failed in the case where we had a very long line. 


```
line 21, column 33:
    lorem ipsum foo_etal_2024 dolor sit amet blah blah
line wrap happens blah blah blah and now it looks bad
                            ^
```

2024-07-16 21:50 UTC, AmitMY approved these changes

2024-07-16 21:50 UTC, merged