Add some missing references
sign-language-processing/sign-language-processing.github.io pull request #117
Opened 2024-10-13 14:24 UTC by ycmin95

Added missing references: cheng2020fully, min2021visual, jiao2023cosign, zhou2023gloss, jiao2024visual.
Plan to include more references from [VIPL-SLP/awesome-sign-language-processing](https://github.com/VIPL-SLP/awesome-sign-language-processing) in future updates.

2024-10-15 13:20 UTC, AmitMY requested changes
Thank you very much for your contribution, happy to see you join the effort :) 

I left a few comments for minor changes.

For future PRs, I find it easier to review PRs that add a single paragraph / refer to a single topic (with a few citations). It makes it so I can review even if I have less time, and merge some changes while waiting for changes for others (just a preference).

2024-10-16 06:49 UTC, ycmin95 commented
Thank you for your comprehensive feedback. I have revised relevant parts and restructured the sentences for clarity. Additionally, I’ve discovered that incorporating hyperlinks for each reference can greatly enhance the document’s usability.

2024-10-16 06:50 UTC, ycmin95 commented on src/references.bib
> +  title={CoSign: Exploring co-occurrence signals in skeleton-based continuous sign language recognition},
Thanks for the suggestion, I revised this reference item.

2024-10-16 06:54 UTC, ycmin95 commented on src/index.md
> +@jiang2021sign propose a novel Skeleton Aware Multi-modal Framework with a Global Ensemble Model (GEM) for isolated SLR (SAM-SLR-v2) to learn and fuse multimodal feature representations. Specifically
I have divided this paragraph into individual sentences to more clearly highlight the distinctions. Besides, in the previous version, I changed the tense of the previous sentence from past tense to present tense (@jiang2021sign proposed -> @jiang2021sign propose), and I recover the original version in the updated version. 

Currently, it appears that the tenses in this project are not consistent and may require an overall review and correction.

2024-10-16 06:57 UTC, ycmin95 commented on src/index.md
> +@dafnis2022bidirectional work on the same modified WLASL dataset as @jiang2021sign, but do not require multimodal data input. Instead, they propose a bidirectional skeleton-based graph convolutional
Thanks for pointing out, I am not accustomed to the boundary here, so I have made changes here :）

2024-10-16 06:57 UTC, ycmin95 commented on src/index.md
> +and use this gloss video segments encoding to optimize the sequence learning model. @cheng2020fully propose a fully convolutional networks for continuous SLR,
Thanks for the suggestion, I revised this sentence.

2024-10-16 06:58 UTC, ycmin95 commented on src/index.md
> +moving away from LSTM-based methods to achieve end-to-end learning. They introduce a gloss feature enhancement (GFE) module to provide additional rectified supervision and
Thanks for the suggestion, I revised this sentence.

2024-10-16 06:58 UTC, ycmin95 commented on src/index.md
> +@jiao2024visual propose a visual alignment pre-training framework for gloss-free sign language translation. Specifically, they adopt Cosign-1s [@jiao2023cosign] to obtain skeleton features from estim
CoSign, thanks!

2024-10-16 06:59 UTC, ycmin95 commented on src/index.md
> +constraint (VEC) and visual alignment constraint (VAC) to strengthen the visual extractor and align long- and short-term predictions, enabling LSTM-based methods to be trained in an end-to-end manner
Thanks for the suggestion, I have capitalized them.

2024-10-16 06:59 UTC, ycmin95 commented on src/index.md
> +@zhou2023gloss propose the GFSLT-VLP framework for gloss-free sign language translation, which improves SLT performance through visual-alignment pretraining. In the pretraining stage, they design a p
Thanks for the suggestion, I have revised this sentence.

2024-10-16 06:59 UTC, ycmin95 commented on src/index.md
> +used in pretraining with a pretrained translation module. This skeleton-based approach achieves state-of-the-art results on the RWTH-PHOENIX-Weather-2014T [@cihan2018neural], CSL-Daily [@dataset:Zhou
The space has been added.

2024-10-16 07:27 UTC, AmitMY approved these changes
Great job!

2024-10-16 07:27 UTC, merged