detection:pal2023importance and momeni2022automatic
sign-language-processing/sign-language-processing.github.io pull request #22
Opened 2023-03-26 12:26 UTC by J22Melody

2023-03-26 12:27 UTC, J22Melody commented on src/references.bib
> +% TODO: where to categorize this?
could be video to gloss, but not a recognition model I would say

2023-03-28 09:19 UTC, AmitMY requested changes

2023-03-28 09:19 UTC, AmitMY commented on src/index.md
> +we need well-annotated data that include interference and distractions with non-signing instances for proper real-world evaluation. @detection:pal2023importance perform a detailed analysis of the eff
```
 of signer overlap
```

Took me a while to understand that this means between the train and test sets.

My suggestion is:

> @detection:pal2023importance conducts a detailed analysis of the impact of signer overlap between the training and test sets on two sign detection benchmark datasets (Signing in the Wild [@missing-citation] and the DGS corpus [@dataset:hanke-etal-2020-extending]) used by @detection:borg2019sign and @detection:moryossef2020real. By comparing the accuracy with and without overlap, they notice a relative decrease in performance. As a result, they suggest new dataset partitions that eliminate overlap and facilitate a more accurate evaluation of performance.

(Please note the `missing-citation`)

2023-03-28 09:19 UTC, AmitMY commented on src/references.bib
> +% TODO: where to categorize this?
yeah i think this is video-to-gloss. 
It is recognition, via a pipeline and combination of models, as far as I understand

2023-03-28 10:21 UTC, J22Melody commented on src/index.md
> +we need well-annotated data that include interference and distractions with non-signing instances for proper real-world evaluation. @detection:pal2023importance perform a detailed analysis of the eff
thanks, have applied and added the missing citation (a bit redundant since it points to the same paper though, a very minor issue)

2023-03-28 10:23 UTC, J22Melody commented on src/references.bib
> +% TODO: where to categorize this?
yes, I see it a bit differently since it's not a pure video-to-gloss model, but a comprehensive pipeline aimed at dense annotation. I have added a few words, let me know whether it makes sense.

2023-03-28 11:03 UTC, merged