update for EACL2023
sign-language-processing/sign-language-processing.github.io pull request #24
Opened 2023-05-02 18:48 UTC by J22Melody

2023-05-02 18:48 UTC, J22Melody commented on src/references.bib
> -% TODO: update this once the EACL citation is out.
wrong place

2023-05-02 18:49 UTC, J22Melody commented on src/references.bib
> +@inproceedings{jiang2022machine,
should be here

2023-05-03 06:21 UTC, AmitMY requested changes
I hope you are having a nice time in Croatia!

2023-05-03 06:21 UTC, AmitMY commented on src/references.bib
> -% TODO: update this once the EACL citation is out.
Please remove the following 5 lines

2023-05-03 06:21 UTC, AmitMY commented on src/references.bib
> +@inproceedings{jiang2022machine,
Please modify in the text to cite as `jiang2022machine` instead of `jiang2021machine`.
Also, please remove the abstract from this file, there's no need.

2023-05-03 14:42 UTC, J22Melody commented on src/references.bib
> +@inproceedings{jiang2022machine,
There is no `jiang2021machine`, only another work `jiang2021sign`

2023-05-04 08:12 UTC, merged