Add BOBSL, ISL-HS, Sign-BD datasets to the datasets table and references.bi
sign-language-processing/sign-language-processing.github.io pull request #28
Opened 2024-03-22 23:13 UTC by cleong110

Closes #27 if accepted

2024-03-23 08:43 UTC, AmitMY requested changes

2024-03-23 08:43 UTC, AmitMY commented on src/datasets/BOBSL.json
> +    "contact": "Samuel Albanie albanie[AT]robots.ox.ac.uk"
i’d change the contact to a real email address

2024-03-23 08:43 UTC, AmitMY commented on src/references.bib
> +  abstract = {Recently, sign language researchers have turned to sign language interpreted TV broadcasts, comprising (i) a video of continuous signing and (ii) subtitles corresponding to the audio co
i think for making this file not huge, we decided to not include abstracts

2024-03-23 08:43 UTC, AmitMY commented on src/datasets/ISL-HS.json
> +      "publication": "dataset:oliveiraDatasetIrishSign2017",
missing citation from bib

2024-03-23 08:43 UTC, AmitMY commented on src/datasets/BOBSL.json
> +    "language": "British Sign Language (BSL)",
Should be "British"

2024-03-23 08:43 UTC, AmitMY commented on src/datasets/ISL-HS.json
> +    "language": "Irish Sign Language (ISL)",
should be "Irish"

2024-03-23 08:43 UTC, AmitMY commented on src/datasets/ISL-HS.json
> +    "#samples": "468 videos available, 58,114 images extracted to show 23 handshapes",
While here I'd say that more details are better, please consider how this is displayed:
I think less information should be present, but if you still wanted to include the entire text, I'd say narrow it to
"468 videos → 58,114 images → 23 handshapes"
![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/5757359/60b3efc2-b1fb-487c-a8bf-74f6c7c8b3e7)

2024-03-25 16:49 UTC, cleong110 commented on src/datasets/ISL-HS.json
> +      "publication": "dataset:oliveiraDatasetIrishSign2017",
So it is, fixing that

2024-03-25 16:52 UTC, cleong110 commented on src/datasets/ISL-HS.json
> +    "language": "Irish Sign Language (ISL)",
fixed

2024-03-25 16:52 UTC, cleong110 commented on src/datasets/BOBSL.json
> +    "language": "British Sign Language (BSL)",
fixed

2024-03-25 16:53 UTC, cleong110 commented on src/datasets/BOBSL.json
> +    "contact": "Samuel Albanie albanie[AT]robots.ox.ac.uk"
Ah yes, copy-pasted that from the project website, good suggestion

2024-03-25 18:34 UTC, AmitMY approved these changes

2024-03-25 18:34 UTC, merged