Add "Linguistically Motivated Segmentation" paper
sign-language-processing/sign-language-processing.github.io pull request #29
Opened 2024-03-26 19:30 UTC by cleong110

2024-03-26 21:34 UTC, AmitMY requested changes

2024-03-26 21:34 UTC, AmitMY commented on src/index.md
> +segmentation:moryossefLinguisticallyMotivatedSign2023 presented a method motivated by linguistic cues ob-
should start with `@`

2024-03-26 21:34 UTC, AmitMY commented on src/references.bib
> +}
should use citation from proceedings
```bib
@inproceedings{moryossef-etal-2023-linguistically,
    title = "Linguistically Motivated Sign Language Segmentation",
    author = {Moryossef, Amit  and
      Jiang, Zifan  and
      M{\"u}ller, Mathias  and
      Ebling, Sarah  and
      Goldberg, Yoav},
    editor = "Bouamor, Houda  and
      Pino, Juan  and
      Bali, Kalika",
    booktitle = "Findings of the Association for Computational Linguistics: EMNLP 2023",
    month = dec,
    year = "2023",
    address = "Singapore",
    publisher = "Association for Computational Linguistics",
    url = "https://aclanthology.org/2023.findings-emnlp.846",
    doi = "10.18653/v1/2023.findings-emnlp.846",
    pages = "12703--12724",
}
```

2024-03-26 21:34 UTC, AmitMY commented on src/references.bib
> +@article{dataset:sehyr2021asl,
you changed the bib id here, but did not change anything related in the text/datasets - probably a bug

2024-03-26 21:34 UTC, AmitMY commented on src/index.md
> +served in sign language corpora, such as prosody (pauses, pace, etc) and handshape changes. They also find that using BIO, an annotation scheme that notes the beginning, inside and outside, makes a s
the word "observed" is broken into two

2024-03-27 14:42 UTC, cleong110 commented on src/references.bib
> +@article{dataset:sehyr2021asl,
Ah, I got halfway through the ASL-LEX.json and then discovered that the video files actually cannot be downloaded. I wasn't sure whether to go ahead and push it up.

2024-03-27 15:47 UTC, cleong110 commented
Made requested changes, I've got a bit of a question still

2024-03-27 17:37 UTC, AmitMY requested changes

2024-03-27 17:37 UTC, AmitMY commented on src/references.bib
> +@article{dataset:sehyr2021asl,
I think that's fine as long as you noted it, and you did

2024-03-27 17:37 UTC, AmitMY commented on src/references.bib
> -@article{sehyr2021asl,
you changed the name of this citation, but didn't change usages of it in `index.md`. that would break the citation.
We should make tests for this

![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/5757359/09a515d6-be7d-4b6d-879e-953d76040300)

2024-03-28 08:25 UTC, AmitMY approved these changes

2024-03-28 08:25 UTC, merged