Add SignBank Dataset
sign-language-processing/sign-language-processing.github.io pull request #3
Opened 2022-01-19 15:20 UTC by J22Melody

Solve https://github.com/sign-language-processing/sign-language-processing.github.io/issues/2

2022-01-19 15:20 UTC, J22Melody commented on src/datasets/SignBank.json
> +    "publication": null,
Any publication? I do not know ...

2022-01-19 15:20 UTC, J22Melody commented on src/datasets/SignBank.json
> +    "year": 2021,
What about the year?

2022-01-21 11:04 UTC, AmitMY requested changes

2022-01-21 11:04 UTC, AmitMY commented on src/datasets/SignBank.json
> +    "year": 2021,
try leaving `null` for now

2022-01-21 11:04 UTC, AmitMY commented on src/datasets/SignBank.json
> +    "text:English"
`text:Multilingual` would be better probably. the left part `text` is from an enum, but the right part `Multilingual` is free form text

2022-01-21 11:04 UTC, AmitMY commented on src/datasets/SignBank.json
> +    "publication": null,
not about signbank, afaik

2022-01-21 13:15 UTC, AmitMY approved these changes

2022-01-21 13:15 UTC, merged