Add ISLTranslate to table.
sign-language-processing/sign-language-processing.github.io pull request #35
Opened 2024-05-10 19:37 UTC by cleong110

Might be good to also add a short summary to the  https://research.sign.mt/#sign-language-recognition-translation-and-production section. Something like "Joshi et al build on code from Camgoz and establish a baseline for ISL-to-English translation", and then also cite 

```
@inproceedings{camgoz2020sign,
  title = {Sign Language Transformers: {{Joint}} End-to-End Sign Language Recognition and Translation},
  booktitle = {Proceedings of the {{IEEE}}/{{CVF}} Conference on Computer Vision and Pattern Recognition},
  author = {Camg{\"o}z, Necati Cihan and Koller, Oscar and Hadfield, Simon and Bowden, Richard},
  year = {2020},
  pages = {10023--10033}
}

```

2024-05-10 19:42 UTC, AmitMY requested changes

2024-05-10 19:42 UTC, AmitMY commented on src/datasets/ISLTranslate.json
> +    "#samples": "31k ISL-English sentence/phrase pairs",
this is too verbose, it will be split into 5 rows in the table

2024-05-10 19:58 UTC, cleong110 commented on src/datasets/ISLTranslate.json
> +    "#samples": "31k ISL-English sentence/phrase pairs",
The "#samples" section? Ah, tried to keep it around the same length as e.g. ASL-LEX, I'll edit down

2024-05-10 20:04 UTC, cleong110 commented on src/datasets/ISLTranslate.json
> +    "#samples": "31k ISL-English sentence/phrase pairs",
done

2024-05-10 20:09 UTC, AmitMY requested changes

2024-05-10 20:09 UTC, AmitMY commented on src/index.md
> +@dataset:joshi-etal-2023-isltranslate introduce ISLTranslate, a large translation dataset for Indian Sign Language based on publicly available educational videos intended for hard-of-hearing children
1. ISL -> `Indian Sign Language` (this one is very prominent, Israeli, Irish, etc)
2. I don't see how this is relevant in this section
  - a. this is not video-to-text because their baseline is actually pose-to-text
  - b. this doesn't say anything about the task, or architecture, it is only about a dataset. See how the page is structured such that this part is about the task (and this paragraph says nothing about the task)
  
I would agree that we currently don't have a specific place to describe dataset papers that don't have any new architecture. Maybe we should create one under resources, below the list of datasets.

2024-05-10 20:52 UTC, cleong110 commented on src/index.md
> +@dataset:joshi-etal-2023-isltranslate introduce ISLTranslate, a large translation dataset for Indian Sign Language based on publicly available educational videos intended for hard-of-hearing children
Oh that is a good point, they are indeed pose to text, my mistake.

2024-05-10 20:52 UTC, cleong110 commented on src/index.md
> +@dataset:joshi-etal-2023-isltranslate introduce ISLTranslate, a large translation dataset for Indian Sign Language based on publicly available educational videos intended for hard-of-hearing children
Lemme fix that

2024-05-10 20:55 UTC, cleong110 commented on src/index.md
> +@dataset:joshi-etal-2023-isltranslate introduce ISLTranslate, a large translation dataset for Indian Sign Language based on publicly available educational videos intended for hard-of-hearing children
I think the idea of adding a section for dataset papers makes sense. I can add one, what would we call it? Just "Dataset Papers"?

2024-05-10 20:57 UTC, cleong110 commented on src/index.md
> +@dataset:joshi-etal-2023-isltranslate introduce ISLTranslate, a large translation dataset for Indian Sign Language based on publicly available educational videos intended for hard-of-hearing children
Alternatively it could go in a section such as Resources -> Continuous sign corpora

2024-05-11 07:26 UTC, AmitMY commented on src/index.md
> +@dataset:joshi-etal-2023-isltranslate introduce ISLTranslate, a large translation dataset for Indian Sign Language based on publicly available educational videos intended for hard-of-hearing children
I think another sub-section under `Resources` named `Dataset Papers` can be good. we can always rethink later

2024-05-13 14:40 UTC, cleong110 commented on src/index.md
> +@dataset:joshi-etal-2023-isltranslate introduce ISLTranslate, a large translation dataset for Indian Sign Language based on publicly available educational videos intended for hard-of-hearing children
Added a sub-section and a brief paragraph introducing it

2024-05-13 21:11 UTC, AmitMY approved these changes

2024-05-13 21:11 UTC, merged