Adding "Querying A Sign Language Dictionary with Videos Using Dense Vector Search" and add SL Retrieval section
sign-language-processing/sign-language-processing.github.io pull request #38
Opened 2024-05-16 21:37 UTC by cleong110

Adding https://ieeexplore.ieee.org/document/10193531, aka costerQueryingSignLanguage2023

Note that I also added it to a new section, "Sign Language Retrieval", to which I intend to add https://arxiv.org/abs/2303.12793 as well. Would appreciate thoughts on whether that makes sense, or we ought to add the paper elsewhere/organize things differently.

2024-05-17 06:36 UTC, AmitMY requested changes

2024-05-17 06:36 UTC, AmitMY commented on src/index.md
> +<!-- with video -->
redundant comment

2024-05-17 06:36 UTC, AmitMY commented on src/index.md
> +#### Sign Video to Sign Video
at the moment, this is a redundant title. 

Having a section with a single subsection is usually considered bad style: most style guides, academic or not, advise against it. In particular, [the Chicago Manual of Style advises against it](http://www.chicagomanualofstyle.org/qanda/data/faq/topics/Subheads.html?old=Subheads01.html).

2024-05-17 06:36 UTC, AmitMY commented on src/index.md
> +@costerQueryingSignLanguage2023 present a proof of concept for a sign language dictionary that allows users to search by signing. Users can record a video of themselves signing and upload it to query
I did it for your previous PR, but please do it for this one - Every sentence needs to be on a new line, otherwise, I can only leave comments on the entire text and changes are recorded on the entire text.

2024-05-17 06:36 UTC, AmitMY commented on src/index.md
> +Sign Language Retrieval is the task of finding a particular data item, given some input. In contrast to translation or generation or production tasks, there exists a correct corresponding piece of da
I did it for your previous PR, but please do it for this one - Every sentence needs to be on a new line, otherwise, I can only leave comments on the entire text and changes are recorded on the entire text.

2024-05-17 06:36 UTC, AmitMY commented on src/references.bib
> +  title = {Querying {{A Sign Language Dictionary}} with {{Videos Using Dense Vector Search}}},
Why did you add `{{}}` all over? or did you copy this from somewhere?

2024-05-20 16:43 UTC, cleong110 commented on src/references.bib
> +  title = {Querying {{A Sign Language Dictionary}} with {{Videos Using Dense Vector Search}}},
... and change the key to `costerQueryingSignLanguage2023`

2024-05-20 16:44 UTC, cleong110 commented on src/index.md
> +Sign Language Retrieval is the task of finding a particular data item, given some input. In contrast to translation or generation or production tasks, there exists a correct corresponding piece of da
Right! Thought I'd done it for this already, added to my checklist.

2024-05-20 16:48 UTC, cleong110 commented on src/index.md
> +#### Sign Video to Sign Video
That makes sense! If and when we add more content it might make sense to subdivide but like this it just looks a bit odd and redundant, yes.

2024-05-20 16:53 UTC, cleong110 commented on src/references.bib
> +  title = {Querying {{A Sign Language Dictionary}} with {{Videos Using Dense Vector Search}}},
Advice on citation workflow appreciated. Thus far I've been relying on Zotero to automate much of this, along with a manual step to be sure I'm searching Semantic Scholar for the Official citation if one exists, e.g. the ACL Anthology version.

2024-05-20 16:58 UTC, AmitMY commented on src/references.bib
> +  title = {Querying {{A Sign Language Dictionary}} with {{Videos Using Dense Vector Search}}},
I just semantic-scholar, and if not, google scholar, usually.
the key itself is not very important, if you see a bad key, like `10193531` you can always invent one: `costerQuery2023` for example.
The text in the title should be without `{{}}` unless it is a word that has special capitalization properties ({{LLMs}, {{LLaMA}} or {{BERT}} for example.

2024-05-20 17:13 UTC, AmitMY requested changes

2024-05-21 19:57 UTC, cleong110 commented on src/index.md
> +[A prototype repository](https://github.com/m-decoster/VGT-SL-Dictionary) is available, including scripts for database generation and documentation for model installation or training.
Fair enough. Don't need to add a features list to every one. Maybe for my Coder's guide, but here we're more interested in brief descriptions of theory, approach, etc.

2024-05-21 20:00 UTC, cleong110 commented on src/references.bib
> +  doi={10.1109/ICASSPW59220.2023.10193531}}
I'll give prettybib a try! If it makes many changes I will probably submit a separate pull request for that

2024-05-21 20:13 UTC, cleong110 commented on src/index.md
> +The process begins with pretraining a [Sign Language Recognition model](#pose-to-gloss) to embed sign inputs.
"a subset of the VGT Corpus" apparently, which they cite as 

```
M. Van Herreweghe, M. Vermeerbergen, E. Demey, H. De Durpel, H. Nyffels, and S. Verstraete, “Het corpus vgt. een digitaal open access corpus van videos and annotaties van vlaamse gebarentaal, ontwikkeld aan de universiteit gent ism ku leuven,” 2015.
```

Presumably https://corpusvgt.be/. ... do we add that as a part of _this_ pull request, or make a new and separate one for that?

2024-05-22 12:54 UTC, AmitMY commented on src/index.md
> +Sign Language Retrieval is the task of finding a particular data item, given some input. In contrast to translation or generation or production tasks, there exists a correct corresponding piece of da
`there exists a correct corresponding piece of data already, the task is simply to find the correct one out of many`

my quick draft:
> there **can** exist a corresponding piece of data, and the task is to find it out of many, if at all it exists

2024-05-22 18:11 UTC, cleong110 commented on src/index.md
> +They pretrain a [Sign Language Recognition model](#pose-to-gloss) on a subset of the [VGT corpus](https://corpusvgt.be/) to embed sign inputs.
It was in Dutch but I think I found the official citation: 
```
@misc{6973686,
  abstract     = {{Het Corpus VGT is een verzameling van video’s in Vlaamse Gebarentaal. We verzamelden in totaal meer dan 5 TB of 140 uren video. 120 dove mensen werkten mee aan het Corpus VGT als informanten. Bij het selecteren van de informanten werd rekening gehouden met leeftijd, regio en gender. Per twee gaven we hen een reeks thema’s om over te praten: vertellen van een verhaal, maken van afspraken, discussiëren over een thema, vertellen over hun schooltijd enz. Deze conversaties namen we op video op en we monteerden ze per opdracht. De gesprekken in Vlaamse Gebarentaal annoteerden we vervolgens door ze te glossen.

Het Corpus VGT is gemaakt om onderzoek naar Vlaamse Gebarentaal te doen. Omdat er in andere landen ook al gebarentaalcorpora zijn samengesteld, kan men ook vergelijkend onderzoek tussen Vlaamse Gebarentaal en andere gebarentalen doen. Daarnaast kunnen docenten het corpus gebruiken in hun lessen Vlaamse Gebarentaal. Het Corpus VGT is ook een middel om Vlaamse Gebarentaal en aspecten van de Vlaamse Dovencultuur te documenteren en te bewaren.}},
  author       = {{Van Herreweghe, Mieke and Vermeerbergen, Myriam and Demey, Eline and De Durpel, Hannes and Nyffels, Hilde and Verstraete, Sam}},
  keywords     = {{Vlaamse Gebarentaal,Corpuslinguïstiek}},
  language     = {{dut}},
  title        = {{Het Corpus VGT. Een digitaal open access corpus van videos and annotaties van Vlaamse Gebarentaal, ontwikkeld aan de Universiteit Gent ism KU Leuven. <www.corpusvgt.be>}},
  url          = {{http://www.corpusvgt.ugent.be/}},
  year         = {{2015}},
}
```

2024-05-22 18:12 UTC, cleong110 commented on src/index.md
> +They pretrain a [Sign Language Recognition model](#pose-to-gloss) on a subset of the [VGT corpus](https://corpusvgt.be/) to embed sign inputs.
Following our normal convention this would be added as `dataset:herreweghe2015VGTCorpus

2024-05-22 21:44 UTC, AmitMY approved these changes

2024-05-22 21:46 UTC, merged