Adding "Two-Stream Network for Sign Language Recognition and Translation"
sign-language-processing/sign-language-processing.github.io pull request #42
Opened 2024-05-22 20:29 UTC by cleong110

Paper link: https://papers.nips.cc/paper_files/paper/2022/hash/6cd3ac24cdb789beeaa9f7145670fcae-Abstract-Conference.html

My notes on this, including initial summary, ChatGPT rewrite suggestions, etc: https://github.com/cleong110/sign-language-processing.github.io/issues/9

2024-05-22 21:56 UTC, AmitMY requested changes

2024-05-22 21:56 UTC, AmitMY commented on src/index.md
> +If BLEU is used, compute it with SacreBLEU,
cite BLEU here, cite SacreBLEU (because we are talking about them, not in passing)

2024-05-22 21:56 UTC, AmitMY commented on src/index.md
> +tokenization for gloss outputs.
make the three above rows, one line. guideline is to only break lines on periods, to make full sentences

2024-05-22 21:56 UTC, AmitMY commented on src/index.md
> +* Optimize gloss translation baselines with methods shown to be effective for low-resource MT.
I don't expect that you expect it, but it looks like this: (https://dillinger.io/)
<img width="721" alt="image" src="https://github.com/sign-language-processing/sign-language-processing.github.io/assets/5757359/6e683dfc-6169-469a-9d11-782479ce70f4">

2024-05-22 21:56 UTC, AmitMY commented on src/index.md
> +despite recent works such as @yin-read-2020-better and @muller-etal-2023-considerations claim that glosses are an inefficient representation of sign language,
good catch!

2024-05-22 21:56 UTC, AmitMY commented on src/index.md
> +@chen2022TwoStreamNetworkSign present a two-stream network for sign language recognition (SLR) and translation (SLT), utilizing a dual visual encoder architecture to encode RGB video frames and pose
break into lines.
space after `mBART` before citation 

Great writing otherwise!

2024-05-23 16:13 UTC, cleong110 commented on src/index.md
> +* Optimize gloss translation baselines with methods shown to be effective for low-resource MT.
Oh that's helpful! I can preview it in VS Code as well, but this tool makes it really easy to check small sections

2024-05-23 16:22 UTC, cleong110 commented on src/index.md
> +despite recent works such as @yin-read-2020-better and @muller-etal-2023-considerations claim that glosses are an inefficient representation of sign language,
Thanks! :)

2024-05-23 16:30 UTC, cleong110 commented
Working on the merge conflict now. It seems I need to: 
1. Sync fork on Github so my version of master is updated
2. `git pull` on my local master
3. `git merge master` in my local version of cleong110:paper/chen2022TwoStreamNetworkSign

2024-05-24 12:09 UTC, AmitMY requested changes
minor corrections

2024-05-24 12:09 UTC, AmitMY commented on src/index.md
> +For SLT the visual encoders, based on an S3D backbone [@xie2018SpatiotemporalS3D], output to a multilingual translation network built on mBART [@liu-etal-2020-multilingual-denoising].
This fractured sentence is strange.
Moving a comma about:
> For SLT, the visual encoders based on an S3D backbone [@xie2018SpatiotemporalS3D] output to a multilingual

2024-05-24 12:09 UTC, AmitMY commented on src/index.md
> +For SLT the visual encoders, based on an S3D backbone [@xie2018SpatiotemporalS3D], output to a multilingual translation network built on mBART [@liu-etal-2020-multilingual-denoising].
`build on` - i think should be `built using` or just `using`

2024-05-24 13:05 UTC, cleong110 commented on src/index.md
> +For SLT the visual encoders, based on an S3D backbone [@xie2018SpatiotemporalS3D], output to a multilingual translation network built on mBART [@liu-etal-2020-multilingual-denoising].
Yeah that's better

2024-05-25 07:51 UTC, merged