Adding "Towards Privacy-Aware Sign Language Translation at Scale"
sign-language-processing/sign-language-processing.github.io pull request #43
Opened 2024-05-23 17:37 UTC by cleong110

Recent, interesting paper. 

pro:  SOTA on How2Sign, self-supervised seems quite useful, potential code release. Also I recognize the authors and they've done interesting stuff.
con: still a preprint, code not yet out. 

###### My notes 
https://github.com/cleong110/sign-language-processing.github.io/issues/11 my notes detailing things, incl. various drafts of the summary, iterating w/ help of ChatGPT, etc.

Has me thinking about if blurring really works for anonymization, isn't it reversible?

2024-05-25 08:02 UTC, AmitMY requested changes

2024-05-25 08:02 UTC, AmitMY commented on src/index.md
> +In the second stage, the vision model's outputs are fed into a multilingual language model (T5) for finetuning on the How2Sign dataset [@raffel2020T5Transformer; @dataset:duarte2020how2sign].
same here:

> In the second stage, the vision model's outputs are fed into a multilingual language model [@raffel2020T5Transformer] for finetuning on the How2Sign dataset [@dataset:duarte2020how2sign].

2024-05-25 08:02 UTC, AmitMY commented on src/index.md
> +To mitigate privacy risks, the framework employs facial obfuscation.
i think there is a need to expand on this line. this is the main part of the title.
they obfuscate - when? pretraining? fine tuning? what does it cause?

2024-05-25 13:05 UTC, cleong110 commented on src/index.md
> +To mitigate privacy risks, the framework employs facial obfuscation.
Good point. Facial blurring during pretraining of the visual encoder using an "internal face blurring software". They tried blurring in the different stages and decided that doing it in the visual encoder pretraining step only gave the best anonymization/performance tradeoff.
![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/122366389/d13e45bb-2be5-4594-bede-034b76c58914)

2024-05-25 13:06 UTC, cleong110 commented on src/index.md
> +To mitigate privacy risks, the framework employs facial obfuscation.
![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/122366389/fda38183-f96f-4b32-b1ad-fa28e910b13a)

2024-05-25 13:06 UTC, cleong110 commented on src/index.md
> +To mitigate privacy risks, the framework employs facial obfuscation.
I'll do a further rewrite Monday.

2024-05-26 09:45 UTC, AmitMY commented on src/index.md
> +To mitigate privacy risks, the framework employs facial obfuscation.
The last sentence is the important one - so something like:
"while pertaining with blurring hurts performance, some performance can be recovered when fine tuning on unblurred data. They conclude that SLT models can be pretrained in a privacy-aware manner without sacrificing too much performance."

2024-05-27 21:43 UTC, cleong110 commented on src/index.md
> +To mitigate privacy risks, the framework employs facial obfuscation.
Did a new version. I wonder if it would be good to emphasize a bit more why this is interesting: even though the visual encoder was only ever trained with blurred data and is then frozen, the finetuning still makes up a good amount of performance. So there's not really any way for the model to "learn" anyone's face it seem

2024-05-28 06:15 UTC, AmitMY requested changes

2024-05-28 06:15 UTC, AmitMY commented on src/index.md
>  SSVP-SLT achieves state-of-the-art performance on How2Sign [@dataset:duarte2020how2sign].
I think this line should be before `they conclude`
but the text is good.

2024-05-29 20:03 UTC, AmitMY approved these changes

2024-05-29 20:04 UTC, merged