Update BosphorusSign
sign-language-processing/sign-language-processing.github.io pull request #49
Opened 2024-05-25 12:39 UTC by cleong110

Updating BosphorusSign details including broken link, adding features for Kinectv2.

TODO a second pull request adding BosphorusSign22k, the updated release

https://github.com/sign-language-processing/sign-language-processing.github.io/issues/48 details.

2024-05-26 09:41 UTC, AmitMY requested changes

2024-05-26 09:41 UTC, AmitMY commented on src/datasets/BosphorusSign.json
> +  "#samples": "22,670 Samples",
> BosphorusSign Turkish Sign Language corpus, which consists of 855 sign and p

https://aclanthology.org/L16-1220.pdf

Where is this info from? this is the number for Bosphorus22K, no?

2024-05-27 14:09 UTC, cleong110 commented on src/datasets/BosphorusSign.json
> +  "#samples": "22,670 Samples",
Table 3 of the 22k paper lists statistics for both datasets. 
![333638579-10e469cc-8511-41f0-99a6-5416479ba427](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/122366389/0a192158-1f2a-4c5a-a2d4-3a3f3469680a)

2024-05-27 14:34 UTC, cleong110 commented on src/datasets/BosphorusSign.json
> +  "#samples": "22,670 Samples",
In the original BosphorusSign citation the number given is 855, not 636 or 595, we have:
* "The corpus contains 855 signs" in the conclusion section
* Table 2 talks about modalities/features
* Table 1 talks about _other_ datasets
* "We have collected 855 signs and phrase samples..." in the introduction section
* "When completed, the corpus will have at least six repetitions of each sign per-
formed by 10 signers, giving a wide variance to the data."

What I presume happened is that between the two papers they decided to trim down the "publicly available" data to 595 signs.

2024-05-27 14:41 UTC, cleong110 commented on src/datasets/BosphorusSign.json
> +  "#samples": "22,670 Samples",
It also seems that for whatever reason the "when completed... 10 signers" did not happen, as the newer citation lists only 6, and has this to say:

> Our dataset is based on the BosphorusSign (Cam-
goz et al., 2016c) corpus which was collected with the pur-
pose of helping both linguistic and computer science com-
munities. It contains isolated videos of Turkish Sign Lan-
guage glosses from three different domains: Health, finance
and commonly used everyday signs. Videos in this dataset
were performed by six native signers, as shown in Figure
1, which makes this dataset valuable for user independent
sign language studies.

"this dataset" I interpreted to mean that BosphorusSign, meaning that both BosphorusSign and BosphorusSign22k have the same number of signers, namely 6.

2024-05-28 09:39 UTC, AmitMY commented on src/datasets/BosphorusSign.json
> +  "#samples": "22,670 Samples",
i think overall stats are more "correct" to use. thanks for checking!

2024-05-29 20:05 UTC, AmitMY approved these changes

2024-05-29 20:05 UTC, merged