Adding SignBERT+
sign-language-processing/sign-language-processing.github.io pull request #54
Opened 2024-05-28 14:16 UTC by cleong110

Adding SignBERT+ summary

Paper: https://ieeexplore.ieee.org/document/10109128

Detailed description of summary process: https://github.com/cleong110/sign-language-processing.github.io/issues/14

Summary of PR: 

* Adding the paper and summary
* Adding some key references

**Questions:**
* should this be in the pose-to-text section? That is one of the tasks they evaluate on but it's a pretraining framework for general SLU, and they just validate on it. 
* Would it be good to have a general "pretraining" section instead?
* Added a citation for RWTH-PHOENIX-WEATHER (the 2015 continuous SLR set, koller2015ContinuousSLR, not the translation set!), because it seemed we didn't have one. Do we need an explanation somewhere of the distinction between all the different RWTH sets?
* (lower priority) What do we do about the [HANDS17 dataset](https://github.com/cleong110/sign-language-processing.github.io/issues/14#issuecomment-2134004288) or other similar datasets that aren't specifically for SLU but are useful?  
* What do we do about SignBERT (https://openaccess.thecvf.com/content/ICCV2021/html/Hu_SignBERT_Pre-Training_of_Hand-Model-Aware_Representation_for_Sign_Language_Recognition_ICCV_2021_paper.html)? They describe SignBERT+ as an extension of SignBERT, should we mention it?

2024-05-30 07:31 UTC, AmitMY requested changes

2024-05-30 07:31 UTC, AmitMY commented on src/references.bib
> +  title={SignBERT+: Hand-Model-Aware Self-Supervised Pre-Training for Sign Language Understanding},
`{SignBERT}`

2024-05-30 07:31 UTC, AmitMY commented on src/references.bib
> +    title     = {SignBERT: Pre-Training of Hand-Model-Aware Representation for Sign Language Recognition},
`{SignBERT}`

2024-05-30 07:31 UTC, AmitMY commented on src/references.bib
> +	title = {Global-Local Enhancement Network for NMF-Aware Sign Language Recognition},
`{NMF}`

2024-05-30 07:31 UTC, AmitMY commented on src/references.bib
> +      title={The 2017 Hands in the Million Challenge on 3D Hand Pose Estimation},
`{3D}`

2024-05-30 07:31 UTC, AmitMY commented on src/references.bib
> +    title={OpenMMLab Pose Estimation Toolbox and Benchmark},
{OpenMMLab}

2024-05-30 07:31 UTC, AmitMY commented on src/references.bib
> +  title={Attention-Based 3D-CNNs for Large-Vocabulary Sign Language Recognition},
{3D-CNNs}

2024-05-30 07:31 UTC, AmitMY commented on src/datasets/NMFs_CSL.json
> +    "#samples": "32010 videos",
32,010

2024-05-30 07:31 UTC, AmitMY commented on src/index.md
> +@hu2023SignBertPlus introduce SignBERT+, a self-supervised pretraining method for sign language understanding (SLU) incorporating a hand-model-aware approach.
`hand-model-aware` is not a clear compound when reading

2024-05-30 07:31 UTC, AmitMY commented on src/index.md
> +Validation on isolated SLR (MS-ASL [@dataset:joze2018ms], WLASL [@dataset:li2020word], SLR500 [@huang2019attention3DCNNsSLR].), continuous SLR (RWTH-PHOENIX-Weather [@koller2015ContinuousSLR]), and S
dot after SLR500 can be removed

2024-05-30 07:31 UTC, AmitMY commented on src/index.md
> +@hu2023SignBertPlus introduce SignBERT+, a self-supervised pretraining method for sign language understanding (SLU) incorporating a hand-model-aware approach.
Unclear to me how this relates to SignBERT.

Usually it would be:
> .... introduce SignBERT, .....
They then introduce SignBERT+ with better ____ modeling.

2024-05-30 07:31 UTC, AmitMY commented on src/index.md
> +Validation on isolated SLR (MS-ASL [@dataset:joze2018ms], WLASL [@dataset:li2020word], SLR500 [@huang2019attention3DCNNsSLR].), continuous SLR (RWTH-PHOENIX-Weather [@koller2015ContinuousSLR]), and S
Writing is generally good!

2024-05-30 21:15 UTC, cleong110 commented on src/index.md
> +Validation on isolated SLR (MS-ASL [@dataset:joze2018ms], WLASL [@dataset:li2020word], SLR500 [@huang2019attention3DCNNsSLR].), continuous SLR (RWTH-PHOENIX-Weather [@koller2015ContinuousSLR]), and S
Nice catch!

2024-05-30 21:17 UTC, cleong110 commented on src/index.md
> +@hu2023SignBertPlus introduce SignBERT+, a self-supervised pretraining method for sign language understanding (SLU) incorporating a hand-model-aware approach.
Yes, I was wondering about this https://github.com/sign-language-processing/sign-language-processing.github.io/pull/54#issue-2321200142. 

tl;dr it's an... "extension of the conference paper" but they added a few things.

![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/122366389/571bdba4-ec8d-4253-a281-a8ff549fd784)
So I was wondering whether we should try and describe both, or just SignBERT+.

2024-05-30 21:17 UTC, cleong110 commented on src/index.md
> +Validation on isolated SLR (MS-ASL [@dataset:joze2018ms], WLASL [@dataset:li2020word], SLR500 [@huang2019attention3DCNNsSLR].), continuous SLR (RWTH-PHOENIX-Weather [@koller2015ContinuousSLR]), and S
Thanks!! :D

2024-05-30 21:39 UTC, cleong110 commented on src/index.md
> +@hu2023SignBertPlus introduce SignBERT+, a self-supervised pretraining method for sign language understanding (SLU) incorporating a hand-model-aware approach.
Took a crack at weaving it in

2024-05-30 21:40 UTC, cleong110 commented on src/index.md
> +@hu2023SignBertPlus introduce SignBERT+, a self-supervised pretraining method for sign language understanding (SLU) incorporating a hand-model-aware approach.
Rewrote to try and make that a bit smoother.

2024-06-01 14:17 UTC, AmitMY requested changes

2024-06-01 14:17 UTC, AmitMY commented on src/index.md
> +@hu2023SignBertPlus introduce SignBERT+, a self-supervised pretraining method for sign language understanding (SLU) that is aware of and informed by a hand model in its predictions.
convoluted phrasing:
>  that is aware of and informed by

2024-06-01 14:17 UTC, AmitMY commented on src/index.md
> +They then pretrain using multi-level masked modeling (joints, frames, clips) and integrate a statistical hand model [@romero2017MANOHandModel] to constrain the decoder's predictions for anatomical re
I feel like these sentences are just fragments, and don't read well as a paragraph.
My quick draft rewrite would be:

```md
@hu2023SignBertPlus introduce SignBERT+, a self-supervised pretraining method for sign language understanding (SLU).
This is an extension of their earlier SignBERT [@hu2021SignBert], with several improvements.
For pertaining, they extract pose sequences from over 230k videos using MMPose [@mmpose2020].
They then perform multi-level masked modeling (joints, frames, clips) and integrate a statistical hand model [@romero2017MANOHandModel] to constrain the decoder's predictions for anatomical realism and enhance its accuracy.
```

2024-06-03 18:27 UTC, cleong110 commented on src/index.md
> +@hu2023SignBertPlus introduce SignBERT+, a self-supervised pretraining method for sign language understanding (SLU) that is aware of and informed by a hand model in its predictions.
Agreed, tbh

2024-06-03 22:45 UTC, cleong110 commented on src/index.md
> +They then pretrain using multi-level masked modeling (joints, frames, clips) and integrate a statistical hand model [@romero2017MANOHandModel] to constrain the decoder's predictions for anatomical re
Took another crack at i.

2024-06-06 21:54 UTC, AmitMY approved these changes

2024-06-06 21:55 UTC, merged