Adding "CiCo: Domain-Aware Sign Language Retrieval via Cross-Lingual Contrastive Learning"
sign-language-processing/sign-language-processing.github.io pull request #56
Opened 2024-06-03 22:41 UTC by cleong110

Paper: https://openaccess.thecvf.com/content/CVPR2023/html/Bao_CiCo_Domain-Aware_Sign_Language_Retrieval_via_Cross-Lingual_Contrastive_Learning_CVPR_2023_paper.html

Added a summary of the paper, as well as some of the works leading up to it. And also citations to a few related papers. 

https://github.com/cleong110/sign-language-processing.github.io/issues/16 my writing process. 

TODO still: 
- [ ] another editing pass with ChatGPT-assistance for conciseness. 
- [ ] Code and models are available at: https://github.com/FangyunWei/SLRT, maybe add a link.

2024-06-06 22:00 UTC, AmitMY requested changes

2024-06-06 22:00 UTC, AmitMY commented on src/index.md
> +They then use modified string edit distances between these trajectories as a way to find similar videos.
very good!

2024-06-06 22:00 UTC, AmitMY commented on src/index.md
> +They then use cross-lingual contrastive learning [@Radford2021LearningTV] in order to contrast feature/text pairs, mapping them to a shared embedding space.
you use "they then" 3 times in this PR, which makes the reading less "fun". chatgpt can help

2024-06-10 19:58 UTC, cleong110 commented on src/index.md
> +They evaluate on How2Sign [@dataset:duarte2020how2sign] and RWTH-PHOENIX-Weather 2014T dataset [@cihan2018neural], improving by a substantial portion over the previous state of the art method [@Duart
Oh good point

2024-06-10 20:00 UTC, cleong110 commented on src/index.md
> +@athitsos2010LargeLexiconIndexingRetrieval present one of the early works in this task, using a method based on hand centroids and dynamic time warping to enable users to submit videos of a sign and
lol it is not! I think I crossed "on this task" with "in this field" or similar

2024-06-10 20:02 UTC, cleong110 commented on src/index.md
> +@Cheng2023CiCoSignLanguageRetrieval introduce a video-to-text (V2T) and text-to-video (t2V) retrieval method based on cross-lingual contrastive learning.
Good point

2024-06-10 20:10 UTC, cleong110 commented on src/index.md
> +They then use modified string edit distances between these trajectories as a way to find similar videos.
Thanks!!

2024-06-10 20:23 UTC, cleong110 commented on src/index.md
> +Combining the two encoders they then pre-extract features from sign language videos.
I don't think I fully understand either, tbh? 


Best I can gather they...

1. Start with a sign-spotting model from https://www.robots.ox.ac.uk/~vgg/research/bslattend/
> In this work, pseudo-labeling is served as our sign spotting approach to localize isolated signs in untrimmed videos from target sign language retrieval datasets.
>Previous methods [16, 18] **have demonstrated the feasibility of transferring a sign encoder pre-trained on large-scale sign-spotting data into downstream tasks.** We follow this practice and use an I3D network pre-trained on BSL-1K [62], a sign classification dataset collected via sign spotting, as our primary sign encoder. Due to its favorable transfer performance, we term this model as a domain-agnostic sign encoder.

2. For target datasets, finetune a target-dataset-specific sign-spotter? Basically take the high-confidence predictions as labels? I guess because the datasets they're interested don't have timestamps/ are not "sign-spotting" or isolated datasets. Thus the sliding window and the high-confidence predictions
![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/122366389/f19cc749-0825-45c1-8576-d6810da7830d)

3. use both at once in a sort of ensemble:
![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/122366389/ac3c723f-020f-4b8a-a554-1330e09fe983)

2024-06-10 20:25 UTC, cleong110 commented on src/index.md
> +Combining the two encoders they then pre-extract features from sign language videos.
OK, now that I think aloud about this, on say CSL-Daily that makes sense. 
1. Start with your BSL-1K sign-spotter
2. Run a sliding window acros CSL-Daily videos, pull out the really high-confidence ones
3. Use that to train a CSL-Daily sign-spotter.
4. Use both

2024-06-10 20:52 UTC, cleong110 commented
Something else I discovered: a number of citations go to 

```
@dataset:huang2018video
```

which _is_apparently a CSL dataset, but not the _CSL-Daily_ dataset

2024-06-10 21:24 UTC, cleong110 commented
Rewrote with ChatGPT assistance: https://chatgpt.com/share/007fb06b-e6df-468c-a7c3-9c8cc24b9855

2024-06-10 21:25 UTC, cleong110 commented
ChatGPT helped ID misformatted citations, and gave some helpful suggestions. I asked it this time to go line by line explaining changes, some of which I took and some I did not, or adjusted. For example it tried to but T2V and V2T back in

2024-06-10 21:26 UTC, cleong110 commented on src/index.md
> +They then use cross-lingual contrastive learning [@Radford2021LearningTV] in order to contrast feature/text pairs, mapping them to a shared embedding space.
So I do! Fixed

2024-06-11 09:35 UTC, AmitMY requested changes

2024-06-11 09:35 UTC, AmitMY commented on src/index.md
> +Sign Language Retrieval is the task of finding a particular data item, given some input. In contrast to translation, generation or production tasks, there can exist a correct corresponding piece of d
Remove wrong "and"

Metrics used include retrieval at Rank K (R@K, higher is better) and median rank (MedR, lower is better).

2024-06-11 09:35 UTC, AmitMY commented on src/references.bib
> +  title={CiCo: Domain-Aware Sign Language Retrieval via Cross-Lingual Contrastive Learning},
{CiCo}

2024-06-11 09:35 UTC, AmitMY commented on src/index.md
> +Inspired by transfer learning from sign-spotting/segmenting models [@jui-etal-2022-machine;@Duarte2022SignVideoRetrivalWithTextQueries], the authors employ a domain-agnostic I3D encoder, pretrained o
"segmenting" -> "segmentation"

2024-06-11 09:35 UTC, AmitMY commented on src/index.md
> +Inspired by transfer learning from sign-spotting/segmenting models [@jui-etal-2022-machine;@Duarte2022SignVideoRetrivalWithTextQueries], the authors employ a domain-agnostic I3D encoder, pretrained o
datasets (double sapce) for

2024-06-11 09:35 UTC, AmitMY commented on src/index.md
> +The combined encoders pre-extract features from sign language videos.
how are they "combined"? do you mean "both encoders were used to ..."
also in that case, i don't understand which models are "combined" or "both"

2024-06-11 09:35 UTC, AmitMY commented on src/index.md
> +Cross-lingual contrastive learning [@Radford2021LearningTV] is applied to align feature-text pairs within a shared embedding space.
should be merged with the previous sentence. these two fragments don't make sense as individual sentences

2024-06-11 09:35 UTC, AmitMY commented on src/index.md
> +Evaluations on How2Sign [@dataset:duarte2020how2sign] and RWTH-PHOENIX-Weather 2014T datasets [@cihan2018neural] demonstrate significant improvment over the previous state of the art method [@Duarte2
on "the" .... datasets

2024-06-11 09:35 UTC, AmitMY commented on src/index.md
> +Evaluations on How2Sign [@dataset:duarte2020how2sign] and RWTH-PHOENIX-Weather 2014T datasets [@cihan2018neural] demonstrate significant improvment over the previous state of the art method [@Duarte2
"significant" tends to be misused. do they show significance testing? if not, remove that word

2024-06-11 14:20 UTC, cleong110 commented on src/index.md
> +Sign Language Retrieval is the task of finding a particular data item, given some input. In contrast to translation, generation or production tasks, there can exist a correct corresponding piece of d
good catch!

2024-06-11 14:20 UTC, cleong110 commented on src/index.md
> +Sign Language Retrieval is the task of finding a particular data item, given some input. In contrast to translation, generation or production tasks, there can exist a correct corresponding piece of d
Really ought to pull out my[ rubber duck](https://en.wikipedia.org/wiki/Rubber_duck_debugging) for this.

2024-06-11 14:31 UTC, cleong110 commented on src/index.md
> +Evaluations on How2Sign [@dataset:duarte2020how2sign] and RWTH-PHOENIX-Weather 2014T datasets [@cihan2018neural] demonstrate significant improvment over the previous state of the art method [@Duarte2
I could have sworn I put "the" in. 

Significance: based on my opinion/eyeballed it. Recall@1 of 30ish to about 50ish for example seemed like a big bump. I didn't put much thought into it though, thanks for calling it out.

2024-06-11 14:32 UTC, cleong110 commented on src/index.md
> +Evaluations on How2Sign [@dataset:duarte2020how2sign] and RWTH-PHOENIX-Weather 2014T datasets [@cihan2018neural] demonstrate significant improvment over the previous state of the art method [@Duarte2
What actually say:  "outperforms the pioneering method by large margins on various dataset"

2024-06-11 14:55 UTC, cleong110 commented on src/index.md
> +The combined encoders pre-extract features from sign language videos.
Weighted combination of the outputs I believe. 

![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/122366389/e2d7bf11-011c-483b-b5f1-b269135bfb70)
![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/122366389/a39950af-1417-430e-875b-a88573607ef4)
> Our final sign encoder H(·), as shown
in Figure 3a, is a weighted combination of hξ (·) and hθ (·)
with a trade-off hyper-parameter α

2024-06-11 15:14 UTC, cleong110 commented on src/index.md
> +The combined encoders pre-extract features from sign language videos.
![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/122366389/1113215a-8f88-4443-919f-864f95ef08a8)

2024-06-11 16:11 UTC, cleong110 commented
OK, took another crack at CiCo summary

2024-06-12 07:22 UTC, AmitMY requested changes
just one sentence with issues

2024-06-12 07:22 UTC, AmitMY commented on src/index.md
> +Evaluations on How2Sign [@dataset:duarte2020how2sign] and RWTH-PHOENIX-Weather 2014T datasets [@cihan2018neural] demonstrate  improvment over the previous state of the art method [@Duarte2022SignVide
please note, you repeat this issue:
`Evaluations on X and Y datasets` should have a `the`. `Evaluation on the X and Y datasets`

2024-06-12 07:22 UTC, AmitMY commented on src/index.md
> +Evaluations on How2Sign [@dataset:duarte2020how2sign] and RWTH-PHOENIX-Weather 2014T datasets [@cihan2018neural] demonstrate  improvment over the previous state of the art method [@Duarte2022SignVide
The word datasets should come after the citation, not before

2024-06-12 07:22 UTC, AmitMY commented on src/index.md
> +Evaluations on How2Sign [@dataset:duarte2020how2sign] and RWTH-PHOENIX-Weather 2014T datasets [@cihan2018neural] demonstrate  improvment over the previous state of the art method [@Duarte2022SignVide
double space

2024-06-12 07:22 UTC, AmitMY commented on src/index.md
> +Evaluations on How2Sign [@dataset:duarte2020how2sign] and RWTH-PHOENIX-Weather 2014T datasets [@cihan2018neural] demonstrate  improvment over the previous state of the art method [@Duarte2022SignVide
typo: improvement

2024-06-12 07:22 UTC, AmitMY commented on src/index.md
> +Evaluations on How2Sign [@dataset:duarte2020how2sign] and RWTH-PHOENIX-Weather 2014T datasets [@cihan2018neural] demonstrate  improvment over the previous state of the art method [@Duarte2022SignVide
`the previous state of the art method` -> `the previous state of the art`

2024-06-12 18:58 UTC, cleong110 commented on src/index.md
> +Evaluations on How2Sign [@dataset:duarte2020how2sign] and RWTH-PHOENIX-Weather 2014T datasets [@cihan2018neural] demonstrate  improvment over the previous state of the art method [@Duarte2022SignVide
Re: "the previous state of the art method" I was trying to get across that there was only one single paper they compared with. It seems to be a new thing

2024-06-12 18:58 UTC, cleong110 commented on src/index.md
> +Evaluations on How2Sign [@dataset:duarte2020how2sign] and RWTH-PHOENIX-Weather 2014T datasets [@cihan2018neural] demonstrate  improvment over the previous state of the art method [@Duarte2022SignVide
> please note, you repeat this issue: `Evaluations on X and Y datasets` should have a `the`. `Evaluation on the X and Y datasets`

Ah yes, time to add this to my checklist

2024-06-12 20:07 UTC, cleong110 commented on src/index.md
> +Evaluations on How2Sign [@dataset:duarte2020how2sign] and RWTH-PHOENIX-Weather 2014T datasets [@cihan2018neural] demonstrate  improvment over the previous state of the art method [@Duarte2022SignVide
Also, going to give https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker a try

2024-06-13 06:45 UTC, AmitMY approved these changes

2024-06-13 06:46 UTC, merged