Updating NGT Corpus details
sign-language-processing/sign-language-processing.github.io pull request #60
Opened 2024-06-04 19:02 UTC by cleong110

fixes https://github.com/sign-language-processing/sign-language-processing.github.io/issues/58

2024-06-06 11:52 UTC, AmitMY requested changes

2024-06-06 11:52 UTC, AmitMY commented on src/datasets/NGT_Corpus.json
> +  "#samples": "~2375 multi-camera, multi-signer sessions",
i think this should only say "sessions" (it shows in a table, and that is very long)

2024-06-07 15:55 UTC, cleong110 commented on src/datasets/NGT_Corpus.json
> +  "#samples": "~2375 multi-camera, multi-signer sessions",
Roger. I did check to see if it was shorter than other items we have in the same table first. Is there a specific character limit we should aim for, you think?

2024-06-07 19:12 UTC, AmitMY commented on src/datasets/NGT_Corpus.json
> +  "#samples": "~2375 multi-camera, multi-signer sessions",
we could enforce a character limit, right now it is just heuristic: as short as possible

2024-06-07 19:12 UTC, AmitMY approved these changes

2024-06-07 19:12 UTC, merged