Adding "SignBLEU: Automatic Evaluation of Multi-channel Sign Language Translation" and some eval metrics discussion
sign-language-processing/sign-language-processing.github.io pull request #77
Opened 2024-06-12 20:56 UTC by cleong110

https://github.com/cleong110/sign-language-processing.github.io/issues/21 details and checklist

2024-06-14 20:23 UTC, cleong110 commented
All right, I think we're about ready for review: 

https://chatgpt.com/share/2a913f6c-e344-4a00-86ab-357bbae6ec8d is the conversation and revisions of the summary. 

Questions: 

* Do we need to include more detail about the human review process, ethics, etc.?
* How's the use of simple past tense? Style guide talks about this, but unsure whether I ought to say "introduce" or "introduced.
* Do we have a policy of "analyse" vs "analyze"?

2024-06-15 15:48 UTC, AmitMY requested changes

2024-06-15 15:48 UTC, AmitMY commented on src/index.md
> +Methods for automatic evaluation of sign language processing are typically output-dependent.
maybe add "and input-independent", or add the word "only"

2024-06-15 15:48 UTC, AmitMY commented on src/index.md
> +For tasks which output in the form of spoken language text, standard machine translation metrics such as BLEU or ROUGE commonly used.
You can use `#####` - which is the equivalent of `\paragraph`, if that creates more order.

2024-06-15 15:48 UTC, AmitMY commented on src/index.md
> +For tasks which output in the form of spoken language text, standard machine translation metrics such as BLEU or ROUGE commonly used.
missing `are` - `are commonly used`.
ROUGE is not a translation metric - perhaps you should write `BLEU, chrF, or COMET`

2024-06-15 15:48 UTC, AmitMY commented on src/index.md
> +For translation from spoken languages to sign languages, automatic evaluation metrics are an open line of research, though some metrics involving back-translation have been developed (see Text-to-Pos
possible write what `ham2pose` suggests, here.
maybe also need a note about back translation: that people use it (progressive transformers, sign llm), but the outputs are incoherent. this is because people train the backtranslation models on the translation model outputs, and not independently, as one should.

2024-06-15 15:48 UTC, AmitMY commented on src/index.md
> +@kim-etal-2024-signbleu-automatic introduced Multi-Channel Sign Language Translation (MCSLT) and proposed SignBLEU, a BLEU-like scoring method for MCSLT outputs.
in the line above you use present simple tense `analyse`
here you use past tense `introduced`

stick to one - ideally the one we use across the document

2024-06-15 15:48 UTC, AmitMY commented on src/index.md
> +This approach contrasts with traditional single-channel sign language translation (SCSLT), which focused only on manual glosses.
sign language recognition focuses on glosses. translation focuses on text.

2024-06-15 15:48 UTC, AmitMY commented on src/index.md
> +MCSLT includes both manual and non-manual signals, providing a more comprehensive representation of sign language.
signals = annotations?

2024-06-15 15:48 UTC, AmitMY commented on src/index.md
> +The authors concluded that SignBLEU consistently corresponded better to human evaluation than these alternatives.
correspond = correlate?

2024-06-17 19:23 UTC, cleong110 commented on src/index.md
> +Methods for automatic evaluation of sign language processing are typically output-dependent.
Good idea

2024-06-17 19:27 UTC, cleong110 commented on src/index.md
> +For tasks which output in the form of spoken language text, standard machine translation metrics such as BLEU or ROUGE commonly used.
TIL, thanks!

2024-06-17 19:30 UTC, cleong110 commented on src/index.md
> +For tasks which output in the form of spoken language text, standard machine translation metrics such as BLEU or ROUGE commonly used.
You mean, like so? (A)
```
##### For tasks which output in the form of spoken language text, standard machine translation metrics such as BLEU or ROUGE commonly used. 

```

Or do you mean thus? (B)

```
##### Text output
For tasks which output in the form of spoken language text, standard machine translation metrics such as BLEU or ROUGE commonly used. 
```

But (B) would seem to violate the "don't make a new section with only one thing" rule so probably (A)? Not sure what (A) would do actually.

2024-06-17 19:33 UTC, cleong110 commented on src/index.md
> +@kim-etal-2024-signbleu-automatic introduced Multi-Channel Sign Language Translation (MCSLT) and proposed SignBLEU, a BLEU-like scoring method for MCSLT outputs.
Right, past tense is what the style guide recommends, I'll fix it.

2024-06-17 19:36 UTC, cleong110 commented on src/index.md
> +This approach contrasts with traditional single-channel sign language translation (SCSLT), which focused only on manual glosses.
Right, that's how the paper talked about it. 
![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/122366389/16bcf3ad-d0ef-40d8-a7cd-b52d00a21050)

Maybe I could rewrite to clarify that this is their terminology, and that what they describe as Single Channel Sign Language Translation is actually continuous SLR?

2024-06-17 19:38 UTC, cleong110 commented on src/index.md
> +MCSLT includes both manual and non-manual signals, providing a more comprehensive representation of sign language.
How about "annotations for both manual and non-manual signals"?

2024-06-17 19:46 UTC, cleong110 commented on src/index.md
> +MCSLT includes both manual and non-manual signals, providing a more comprehensive representation of sign language.
They use the term a lot. 
![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/122366389/f2828d25-46b3-48c1-a6db-431bca15b230)

I'm not sure annotations is quite right to capture what they're driving at? If you train a model that outputs blocks on multiple channels, and have annotations for those multiple channels, they can calculate a score comparing the two. But the model outputs aren't annotations, right? 

Maybe "MCSLT includes outputs for both manual and non-manual signals in its evaluation"? hmmm

2024-06-17 19:50 UTC, cleong110 commented on src/index.md
> +MCSLT includes both manual and non-manual signals, providing a more comprehensive representation of sign language.
Or we just drop the MCSLT and SCSLT terminology and use the standard terms, e.g. continuous SLR

2024-06-17 20:41 UTC, cleong110 commented on src/index.md
> +For translation from spoken languages to sign languages, automatic evaluation metrics are an open line of research, though some metrics involving back-translation have been developed (see Text-to-Pos
@AmitMY Any citations I could use for do/don't and best practices on backtranslation?

2024-06-17 21:01 UTC, AmitMY commented on src/index.md
> +For tasks which output in the form of spoken language text, standard machine translation metrics such as BLEU or ROUGE commonly used.
I mean B, because it is not a section, is shows as a `\paragraph` in latex.

2024-06-17 21:02 UTC, AmitMY commented on src/index.md
> +For translation from spoken languages to sign languages, automatic evaluation metrics are an open line of research, though some metrics involving back-translation have been developed (see Text-to-Pos
nothing comes to mind. just my passionate hatred for some research...

2024-06-17 21:03 UTC, AmitMY commented on src/index.md
> +MCSLT includes both manual and non-manual signals, providing a more comprehensive representation of sign language.
signals work. drop the strange acronyms and use normal ones

2024-06-17 21:05 UTC, cleong110 commented on src/index.md
> +This approach contrasts with traditional single-channel sign language translation (SCSLT), which focused only on manual glosses.
Rewrote to try and use terminology consistent with the other things we've written.

2024-06-17 21:05 UTC, cleong110 commented on src/index.md
> +MCSLT includes both manual and non-manual signals, providing a more comprehensive representation of sign language.
Gave it a go without the MCSLT and SCSLT terms.

2024-06-18 07:50 UTC, AmitMY requested changes

2024-06-18 07:50 UTC, AmitMY commented on src/index.md
> +Methods for automatic evaluation of sign language processing are typically output-dependent only, and input-independent.
> Methods for automatic evaluation of sign language processing are typically dependent only on the output and independent of the input.


https://chatgpt.com/share/a4f1d2b4-e319-447b-b232-1f4b874c5171

2024-06-18 07:50 UTC, AmitMY commented on src/index.md
> +For tasks which output in the form of spoken language text, standard machine translation metrics such as BLEU, chrF, or COMET are commonly used.
> For tasks that output spoken language text, standard machine translation metrics such as BLEU, chrF, or COMET are commonly used.

2024-06-18 07:50 UTC, AmitMY commented on src/index.md
> +For translation from spoken languages to sign languages, automatic evaluation metrics are an open line of research, though some metrics involving back-translation have been developed (see Text-to-Pos
majority of the text uses "signed languages", but "sign languages" is not a mistake

2024-06-18 07:50 UTC, AmitMY commented on src/index.md
> +For translation from spoken languages to sign languages, automatic evaluation metrics are an open line of research, though some metrics involving back-translation have been developed (see Text-to-Pos
> For translation from spoken languages to sign languages, automatic evaluation metrics are still an open line of research. However, some metrics involving back-translation have been developed (see Text-to-Pose and Notation-to-Pose above).

2024-06-18 07:50 UTC, AmitMY commented on src/index.md
> +@shalev2022ham2pose introduced a metric for pose sequence outputs based on measuring the distance between generated and reference pose sequences.
draft:
Naively, works in this domain have used mean squared error (MSE). However, this metric is flawed as signs are not reproduced on the exact frame level, but are more free over time.
To address that, @shalev2022ham2pose experimented with multiple methods, and introduced a metric for pose sequence outputs based on measuring the distance between generated and reference pose sequences on the joint level using dynamic time warping (I can't remember the name - nDTW-MSEj or something)

2024-06-18 07:50 UTC, AmitMY commented on src/index.md
> +In particular, @muller-etal-2023-considerations analysed this and provide a series of recommendations (see the section on "Glosses", above).
i feel like the order in this section should be text, gloss, notation, pose (not as right now: text, pose, gloss)

2024-06-18 07:50 UTC, AmitMY commented on src/index.md
> +Instead of a single linear sequence of glosses, the representation segmented sign language output into multiple linear channels, each containing discrete "blocks".
the representation `segments`

2024-06-18 07:50 UTC, AmitMY commented on src/index.md
> +Instead of a single linear sequence of glosses, the representation segmented sign language output into multiple linear channels, each containing discrete "blocks".
i think talking about the work in past tense is correct, but talking about the method needs to be in present tense. "the representation segments" "these blocks represent" etc (these blocks did not "represented" and not have a different meaning, but they still do represent)

2024-06-18 07:50 UTC, AmitMY commented on src/index.md
> +The authors concluded that SignBLEU consistently correlated better to human evaluation than these alternatives.
they found, not concluded (in this case)

2024-06-18 12:58 UTC, cleong110 commented on src/index.md
> +For tasks which output in the form of spoken language text, standard machine translation metrics such as BLEU or ROUGE commonly used.
Ah, I see

2024-06-18 12:58 UTC, cleong110 commented on src/index.md
> +Methods for automatic evaluation of sign language processing are typically output-dependent only, and input-independent.
Way better

2024-06-18 13:17 UTC, cleong110 commented on src/index.md
> +@shalev2022ham2pose introduced a metric for pose sequence outputs based on measuring the distance between generated and reference pose sequences.
You got it, "DTW-MJE", or if you do normalized pose sequences, "nDTW-MJE"

2024-06-18 13:18 UTC, cleong110 commented on src/index.md
> +In particular, @muller-etal-2023-considerations analysed this and provide a series of recommendations (see the section on "Glosses", above).
That does seem to flow better, though I can't quite articulate why. I think because pose seems "different."

2024-06-18 13:22 UTC, cleong110 commented on src/index.md
> +The authors concluded that SignBLEU consistently correlated better to human evaluation than these alternatives.
Sure, I'll change it. I'm curious what's the distinction? Is that to indicate more that this was observation, not interpretation?

2024-06-18 13:26 UTC, cleong110 commented on src/index.md
> +The authors concluded that SignBLEU consistently correlated better to human evaluation than these alternatives.
Because there is some uncertainty and room for interpretation there, for example the fact that their human eval involved having people try to exactly re-sign the blockified output, then have others evaluate _that_ for naturalness

2024-06-18 13:29 UTC, cleong110 commented on src/index.md
> +@shalev2022ham2pose introduced a metric for pose sequence outputs based on measuring the distance between generated and reference pose sequences.
> However, it is unclear from the original DTW-MJE definition how to handle missing keypoints, hence we suggest a new distance function that considers missing keypoints and apply DTW-MJE with our distance function over normalized keypoints. We mark this method by nDTW-MJE

2024-06-18 13:34 UTC, cleong110 commented on src/index.md
> +For translation from spoken languages to sign languages, automatic evaluation metrics are an open line of research, though some metrics involving back-translation have been developed (see Text-to-Pos
I think https://aclanthology.org/2022.wmt-1.54.pdf could work perhaps

2024-06-18 13:38 UTC, cleong110 commented on src/index.md
> +For translation from spoken languages to sign languages, automatic evaluation metrics are an open line of research, though some metrics involving back-translation have been developed (see Text-to-Pos
https://www.semanticscholar.org/paper/Back-translation-practices-in-organizational-loss-Klotz-Swider/239bd4331238aefce113096554707aa4e853f272

2024-06-18 13:40 UTC, cleong110 commented on src/index.md
> +For translation from spoken languages to sign languages, automatic evaluation metrics are an open line of research, though some metrics involving back-translation have been developed (see Text-to-Pos
https://www.semanticscholar.org/paper/On-The-Evaluation-of-Machine-Translation-With-Edunov-Ott/8b5b8bd0942d5f39d01c1f4b89d174fb3fde99cc

2024-06-18 13:40 UTC, cleong110 commented on src/index.md
> +For translation from spoken languages to sign languages, automatic evaluation metrics are an open line of research, though some metrics involving back-translation have been developed (see Text-to-Pos
I'm going to break this out into a new issue

2024-06-18 13:41 UTC, cleong110 commented on src/index.md
> +For translation from spoken languages to sign languages, automatic evaluation metrics are an open line of research, though some metrics involving back-translation have been developed (see Text-to-Pos
#83

2024-06-19 05:58 UTC, AmitMY requested changes

2024-06-19 05:58 UTC, AmitMY commented on src/index.md
> +Naively, works in this domain have used mean squared error (MSE). However, this metric is flawed as signs are not reproduced on the exact frame level, but are more free over time.
i know i wrote this sentence, but it was a draft - "free over time" and "on the exact frame level" are vague concepts

2024-06-19 05:58 UTC, AmitMY commented on src/index.md
> +@shalev2022ham2pose introduced a metric for pose sequence outputs based on measuring the distance between generated and reference pose sequences.
so in that case, who actually proposed DTW-MJE?

2024-06-19 17:10 UTC, cleong110 commented on src/index.md
> +Naively, works in this domain have used mean squared error (MSE). However, this metric is flawed as signs are not reproduced on the exact frame level, but are more free over time.
Right, also in looking over it again I realized that actually DTW-MJE comes from https://dl.acm.org/doi/10.1145/3474085.3475463, so I double-need to rewrite

2024-06-19 17:13 UTC, cleong110 commented on src/index.md
> +Naively, works in this domain have used mean squared error (MSE). However, this metric is flawed as signs are not reproduced on the exact frame level, but are more free over time.
Ham2Pose adds in "what to do if there's missing keypoints". "Towards Fast and High-Quality Sign Language Production" is the one that figures out "what to do if the same sign is longer or shorter"

2024-06-19 18:20 UTC, cleong110 commented
Added some more detail on pose output metrics, and some citations for APE

2024-06-20 13:53 UTC, AmitMY requested changes

2024-06-20 13:53 UTC, AmitMY commented on src/index.md
> +Naively, works in this domain have used metrics such as mean squared error (MSE) or Average Position Error (APE) for pose outputs [ahuja2019Language2PoseNaturalLanguage;ghosh2021SynthesisCompositiona
why is one initialized with capitals, and the other isn't?
also, aren't mse and ape the same thing? can say `Mean Squared Error (MSE), also known as Average...`

2024-06-20 13:53 UTC, AmitMY commented on src/index.md
> +For example, MSE and APE do not account for variations in sequence length, for cases where where the same sign might take different amounts of time to produce.
where where
"different amounts of time" sounds strange to me

2024-06-20 13:53 UTC, AmitMY commented on src/index.md
> +
great.
please remove the empty line, to create a more substantial paragraph. huang & shalev are "connected"

2024-06-20 17:28 UTC, cleong110 commented on src/index.md
> +Naively, works in this domain have used metrics such as mean squared error (MSE) or Average Position Error (APE) for pose outputs [ahuja2019Language2PoseNaturalLanguage;ghosh2021SynthesisCompositiona
VS Code even warned me about that now that I look at it again. Whoops. 

![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/122366389/e949623b-0619-4ffe-94c8-33be28795c07)

2024-06-20 17:33 UTC, cleong110 commented on src/index.md
> +For example, MSE and APE do not account for variations in sequence length, for cases where where the same sign might take different amounts of time to produce.
How about:
```
For example, MSE and APE do not account for variations in sequence length.
The same sign may not always take exactly the same amount of time to produce.
```

Or various options here: https://chatgpt.com/share/e4e5cde3-fccf-4e40-ab2f-5b210db6cf6f

2024-06-21 07:17 UTC, AmitMY approved these changes

2024-06-21 07:17 UTC, merged