add walsh's work from LREC 2022
sign-language-processing/sign-language-processing.github.io pull request #9
Opened 2022-08-04 16:03 UTC by J22Melody

2022-08-04 21:47 UTC, AmitMY requested changes

2022-08-04 21:47 UTC, AmitMY commented on src/index.md
> +@walsh2022changing explore Text to HamNoSys (T2H) translation, with HamNoSys as the target sign language writting notation system. They experiment with both direct T2H and Text to Gloss to HamNoSys (
This should be under `Text-to-Notation` rather than `$X$`.

I'd also like to add the fact that:
- they encode the hamnosys with BPE
- it it not clear whether higher bleu in such a setup does indeed correlate to better performance, as the system can produce likely tokens that do not correspond to existing signs
- their method of creating the parallel text-to-hamnosys data is flawed, as not all sentences have all glosses with hamnosys, so they only filter to sentences which do. then their comparison to text-to-gloss is flawed, because they use only a subset of the data

2022-08-04 21:50 UTC, AmitMY commented on src/index.md
> +@walsh2022changing explore Text to HamNoSys (T2H) translation, with HamNoSys as the target sign language writting notation system. They experiment with both direct T2H and Text to Gloss to HamNoSys (
also, typo `writting`

2022-08-05 10:32 UTC, J22Melody commented on src/index.md
> +@walsh2022changing explore Text to HamNoSys (T2H) translation, with HamNoSys as the target sign language writting notation system. They experiment with both direct T2H and Text to Gloss to HamNoSys (
Good points!

I have added some words about these points, please have a look and feel free to suggest further revision, especially on point 3.

(I was unaware of that, how big is the subset compared to the whole dataset?)

2022-08-05 10:54 UTC, AmitMY approved these changes

2022-08-05 10:55 UTC, AmitMY commented on src/index.md
> +@walsh2022changing explore Text to HamNoSys (T2H) translation, with HamNoSys as the target sign language writting notation system. They experiment with both direct T2H and Text to Gloss to HamNoSys (
the funny thing is that they don't say! I'm ok with merging now, I can show you other critique I have

2022-08-05 11:35 UTC, merged