Feature/dataset deprecation 2
sign-language-processing/sign-language-processing.github.io pull request #92
Opened 2024-06-20 16:39 UTC by cleong110

Based on local testing, it seems to successfully skip datasets with "status":"deprecated". Datasets without status fields are left alone. 

Closes #91.

2024-06-20 19:54 UTC, AmitMY requested changes

2024-06-20 19:54 UTC, AmitMY commented on src/datasets.js
> +// "*" means relevant docs at the end
i am against all these comments. they are redundant, or wrong.

2024-06-20 19:54 UTC, AmitMY commented on src/datasets.js
> +// Import the NodeJS "file system" module *
completely redundant

2024-06-20 19:54 UTC, AmitMY commented on src/datasets.js
> +// "*" means relevant docs at the end
yeah, totally wrong and redundant.

2024-06-20 20:40 UTC, cleong110 commented on src/datasets.js
> +// "*" means relevant docs at the end
Glad I got them reviewed then!

2024-06-20 20:42 UTC, cleong110 commented on src/datasets.js
> +// Import the NodeJS "file system" module *
True, only useful for someone unfamiliar with basic JS syntax I suppose, aka me. I'll take it back out

2024-06-20 20:56 UTC, cleong110 commented on src/datasets.js
> +// "*" means relevant docs at the end
Redundant I understand. 

But which ones are wrong? I spent a good amount of time reading JS documentation, I'd like to know what I misunderstood. 

For example 
> CDL: return unchanged if falsy. Later, falsy values are replaced with ""

is based on reading docs manually.

2024-06-20 20:56 UTC, cleong110 commented on src/datasets.js
> +// "*" means relevant docs at the end
Similarly 

> .sort((a, b) => a.pub.name.toLowerCase() > b.pub.name.toLowerCase() ? 1 : -1); // Sort datasets by publication name *

I think benefits from explanation.

2024-06-20 20:57 UTC, cleong110 commented
Added a v2, took out as many redundant comments as I could. Are the remaining ones correct?

2024-06-21 07:08 UTC, AmitMY requested changes

2024-06-21 07:08 UTC, AmitMY commented on src/datasets.js
> +    // CDL: return unchanged if falsy. Later, falsy values are replaced with ""
redundant

2024-06-21 07:08 UTC, AmitMY commented on src/datasets.js
> +    // If text is a number, convert it to a string
redundant, the code is very explicit

2024-06-21 07:08 UTC, AmitMY commented on src/datasets.js
> +// Colin: gets the proper emoji icon for dataset features.
"Colin" is not a valid comment, the code should exist regardless of the authors

2024-06-21 07:08 UTC, AmitMY commented on src/datasets.js
> +    // CDL: this means that things like pose:OpenPose and pose:MediaPipe get the same icon.
no need for "CDL", it is meaningless. the rest of the comment can be useful

2024-06-21 07:08 UTC, AmitMY commented on src/datasets.js
> +    // Dictionary mapping feature types to emoji
redundant, as it is explicit.
if you want to make it more explicit, change the variable name to `featureEmoji`

2024-06-21 07:08 UTC, AmitMY commented on src/datasets.js
> +const datasets = fs.readdirSync(PATH) // Read all filenames in the directory *
list all file names
why star at the end?

2024-06-21 07:08 UTC, AmitMY commented on src/datasets.js
> +    .map(fName => String(fs.readFileSync(PATH + fName))) // Read each file's content and convert to string *
why star at the end?

2024-06-21 07:08 UTC, AmitMY commented on src/datasets.js
> +console.log('|' + lengths.map((l) => new Array(l).fill('-').join('')).join(' | ') + '|');
this should say "divider row" because the code is really not explicit

2024-06-21 07:08 UTC, AmitMY commented on src/datasets.js
> +
redundant new line

2024-06-21 13:11 UTC, cleong110 commented on src/datasets.js
> +const datasets = fs.readdirSync(PATH) // Read all filenames in the directory *
From previous version, where * meant "relevant docs at the end".

2024-06-21 13:11 UTC, cleong110 commented on src/datasets.js
> +    // CDL: this means that things like pose:OpenPose and pose:MediaPipe get the same icon.
Good point!

2024-06-21 13:12 UTC, cleong110 commented on src/datasets.js
> +// Colin: gets the proper emoji icon for dataset features.
Aight, I'll add a note to the style guide.

2024-06-21 13:30 UTC, cleong110 commented on src/datasets.js
> +    // CDL: return unchanged if falsy. Later, falsy values are replaced with ""
Hmmm I guess so. A Javascript programmer would know all about the concept of "falsy", wouldn't they.

2024-06-21 13:34 UTC, cleong110 commented on src/datasets.js
> +    // Dictionary mapping feature types to emoji
Good idea

2024-06-21 13:39 UTC, cleong110 commented
All right! Made some more updates! Thanks for guidance/suggestions!

2024-06-22 07:48 UTC, AmitMY requested changes
getting closer!

2024-06-22 07:48 UTC, AmitMY commented on src/datasets.js
> +// Colin: gets the proper emoji icon for dataset features.
please also remove it

2024-06-22 07:48 UTC, AmitMY commented on src/datasets.js
> +    // CDL: this means that things like pose:OpenPose and pose:MediaPipe get the same icon.
please also remove it

2024-06-22 07:48 UTC, AmitMY commented on src/datasets.js
> +        continue; //skip to the next one
this comment is not helpful

2024-06-24 15:52 UTC, cleong110 commented on src/datasets.js
> +// Colin: gets the proper emoji icon for dataset features.
Did a ctrl+F, they should be all gone now

2024-06-24 21:06 UTC, AmitMY approved these changes

2024-06-27 18:44 UTC, merged